In [1]:
s='htitoj9.0'
s+='k'
print(s)

htitoj9.0k


In [2]:
v=("bye",)
type(v)

tuple

In [3]:
(*a,*b,*v) #args={*variable}-convert given data type into tuple. 

NameError: name 'a' is not defined

In [ ]:
h.update({4})
print(h)

{3, 4, 5}


In [ ]:
d.upper()

'HELLO'

In [ ]:
a=34
b=34.6
c=34+5j
d="hello"
e=[3,4,5]
f=(3,4,5)
g={3: [4,5]}
h={3,4,5}

In [ ]:
bool(('')),
bool({}),bool((45),),
bool()


False

In [ ]:
b=(2,4,6,7,'hii')
b

(2, 4, 6, 7, 'hii')

In [ ]:
bool(' ') #anything non-zero or non empty is true
bool('') #anything zero or empty is false

False

In [ ]:
#Assignment
#s[0]='W'not possible
#a[0]='Q' done
#b[0]='e' not possible
c2[3]=66
print(c2) #done

#deletion
#s[0]='W'not possible
#a[0]='Q' done
#b[0]='e' not possible
#c[5]=66 done

{'a': 34, 'c': 55, 'g': 44, 5: 66, 3: 66}


In [ ]:
s

'htijohn wtoj9.0k'

In [ ]:
{**c2,**c1} #adding dict

{'a': 34, 'c': 55, 'g': 44, 'h': 4, 'y': 5, 'o': 4}

In [ ]:
c2={'a':34,'c':55,'g':44}
c1={'h':4,'y':5,'o':4}
print(c2)
print(c1)

{'a': 34, 'c': 55, 'g': 44}
{'h': 4, 'y': 5, 'o': 4}


In [ ]:
c['type']='ekalsr'
#insert in dict
c

NameError: name 'c' is not defined

In [ ]:
a=[2,4,6,'hi']
a

[2, 4, 6, 'hi']

In [ ]:
s=s[:3]+'john w'+ s[3:]
s

'htijohn wtoj9.0k'

In [ ]:
[4,5]+[6,7]


[4, 5, 6, 7]

In [7]:
a=34
b=34.6
c=34+5j
d="hello"
e=[3,4,5]
f=(3,4,5)
g={3: [4,5]}
h={3,4,5}

In [5]:
'-'.join('wars')
'#'.join('hi this is new'.split())

'hi#this#is#new'

In [7]:


d.split('oh')


['hello']

In [19]:
#using format function
x=30
y=20
z='ek aesa data jo {} to {}ho'
z= z.format(x,y)
z



'ek aesa data jo 30 to 20ho'

In [18]:
z

'ek aesa data jo 30 to 20ho'

In [26]:
a1= 'ek aesa data {0} ho {1} toh {0} kaafi'
a1=a1.format(x,y)
a1

'ek aesa data 30 ho 20 toh 30 kaafi'

In [27]:
#using f- string
zf = f'ek aisa data jo {x} to {y} hai lekin {x} hi kaafi hai'
zf

'ek aisa data jo 30 to 20 hai lekin 30 hi kaafi hai'

In [ ]:
#1. no input and no output args
#2. input arg but not output args
#3. no input but output args are there 
#4. both are there 
#5 in-place (self update)
#6 non in-place 

In [72]:
g['a']=44

In [76]:


g.get('P','Oh No') #Default value can be given at the same time

'Oh No'

In [77]:
print(g.get('P',))

None


In [78]:
e


[4, 5, 45, 987, 987]

In [80]:
e2=e
e2

[4, 5, 45, 987, 987]

In [81]:
e2.append(60)
e2

[4, 5, 45, 987, 987, 60]

In [ ]:
# Deep copy vs shallow copy


In [ ]:
#suites in python
#statement:
#        Content
 #       Content
#statement:
 #       Content
  #  staement:
   #         more content

statement:
        Content
        Content
statement:
        Content
    staement:
    
    
            more content

In [ ]:
#conditional statement
    #if-elif-else
#looping
    1 while

#conditional statement
    #if-elif-else
#looping
    1 while-else
    2 for-else
    3continue/break
    

In [91]:
a=20
while a>0:
    print('hello')
    a-=3
    if(a<10):
        continue
    print("one more")
else:
    print("aacha ab")    

hello
one more
hello
one more
hello
one more
hello
hello
hello
hello
aacha ab


In [83]:
help(e.copy)


Help on built-in function copy:

copy() method of builtins.list instance
    Return a shallow copy of the list.



In [92]:
for i in range(1,11):
    print(i*'*')

*
**
***
****
*****
******
*******
********
*********
**********


In [73]:
list(g.keys())[1]

'a'

In [48]:



e.remove(3)
e

[4, 5, 45, 987, 987, 987]

In [52]:
e.sort(reverse= False )
e

[4, 5, 45, 987, 987, 987]

In [3]:
e1=['hi','you','hey','how','yup']
e1

['hi', 'you', 'hey', 'how', 'yup']

In [5]:
e1.sort(key=len,reverse=False)
e1

['hi', 'you', 'hey', 'how', 'yup']

In [11]:
f1=list(f)
f1.sort(reverse=True)
f1=tuple(f1)
f1


(5, 4, 3)

In [67]:
tuple(sorted(f,reverse= True))

(5, 4, 3)

In [68]:
k=e.pop()
k

987

In [10]:
!python -m pip install numpy

You should consider upgrading via the 'c:\Users\Naman\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [12]:
A=np.array([5,6,7])
A

array([5, 6, 7])

In [11]:
import numpy as np


In [13]:
A.shape

(3,)

In [20]:
r=np.array([[5,6,7],[7,8,9],[6,0,9]])
r

array([[5, 6, 7],
       [7, 8, 9],
       [6, 0, 9]])

In [17]:
b=np.array([[5,6,7],[3,1,2]])

b

array([[5, 6, 7],
       [3, 1, 2]])

In [26]:
k=np.array([[[3,8,4],[9,3,5],[11,15,17]],[[41,81,71],[31,11,51],[61,91,131]]])
k


array([[[  3,   8,   4],
        [  9,   3,   5],
        [ 11,  15,  17]],

       [[ 41,  81,  71],
        [ 31,  11,  51],
        [ 61,  91, 131]]])

In [30]:

k[1][0]

array([ 61,  91, 131])

In [33]:
k[1,0,0]

41

In [32]:
r[1,0]

7

In [35]:
r[2,0:3:1]

array([6, 0, 9])

In [43]:
k[1,0:3:1]

array([[ 41,  81,  71],
       [ 31,  11,  51],
       [ 61,  91, 131]])

In [45]:
r[2,:3]

array([6, 0, 9])

In [46]:
k[:,1:2]

array([[[ 9,  3,  5]],

       [[31, 11, 51]]])

In [47]:
r[:,1:2]

array([[6],
       [8],
       [0]])

In [50]:
k[1,0:3:1]

array([[ 41,  81,  71],
       [ 31,  11,  51],
       [ 61,  91, 131]])

In [51]:
k[:2,-2:,:1]

array([[[ 9],
        [11]],

       [[31],
        [61]]])

In [52]:
k[-1:,-2:,:]

array([[[ 31,  11,  51],
        [ 61,  91, 131]]])

In [53]:
m=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[3,31]]])

m

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]],

       [[ 6, 61],
        [ 9, 91],
        [ 3, 31]]])

In [54]:
m.shape

(3, 3, 2)

x - Row 
y -Column
w - width of image 
h - height of image 

(150,50)
(60,40)

>>img[50:50+40,150:150+60]

In [61]:
r[0,0]=505
r

array([[505,  55,  55],
       [  7,   8,   9],
       [  6,   0,   9]])

In [64]:
r[2,:]=([4,9,7])
r

array([[505,  55,  55],
       [  4,   6,   7],
       [  4,   9,   7]])

In [70]:
r+3

array([[508,   7,  58],
       [  7,  11,  10],
       [  7,  10,  10]])

In [72]:
r[3:,:]=[1,1,3]
r

array([[505,   4,  55],
       [  4,   8,   7],
       [  1,   1,   3]])

In [76]:
np.append(b,[[1,2,5]],axis=0)  
#axis add

array([[5, 6, 7],
       [3, 1, 2],
       [1, 2, 5],
       [1, 2, 5]])

In [86]:
np.append(r,[[6],[7],[8]], axis=1)  

array([[505,   4,  55,   6],
       [  4,   8,   7,   7],
       [  1,   1,   3,   8]])

In [87]:
np.delete(r,1, axis=1)

array([[505,  55],
       [  4,   7],
       [  1,   3]])

In [ ]:
#array creation function 
np.array()
np.arrange ()
np.linspace()
np.ones()
np.zeros()
np.eye()
randon.randint()