In [9]:
%pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Naman\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [10]:
%pip install scikit-image

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\Naman\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [46]:

%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotlib (from versions: none)
ERROR: No matching distribution found for matplotlib
You should consider upgrading via the 'c:\Users\Naman\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [15]:
np.arange(1,11,1)    #no from 1 to 10 and you can give float number in arange but not in range 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [36]:
np.linspace(2.0,3.0,6)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [31]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:

np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
p=np.ones([4,5], dtype=int)
p

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
p.dtype

dtype('int32')

In [40]:
p.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
p8=p.astype('uint8') #uint8 - is a unsigned int of 8 bit
p8

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

data types used in numpy 
uint8 , unint16 , uint32 , uint64
int8 , int16 ,int32 ,int64
ufloat8 ,u float16 ,ufloat32 ,ufloat64

In [42]:
np.random.randint(1,100,5)

array([46,  6, 29, 18, 20])

In [44]:
np.random.randint(1,100,[3,5])

array([[ 2, 55, 90, 68, 73],
       [65, 98, 76, 95, 67],
       [40,  9, 81, 44, 25]])

In [45]:
np.random.randint(1,100,[3,5])  # gives random value in btw the range 

array([[38, 67, 51, 78, 67],
       [38, 27, 43, 54, 12],
       [56, 44,  4, 79, 41]])

In [50]:
np.random.seed(30)   #seed - randomness among fixed number /control the randomness
np.random.randint(1,100,[3,5])

array([[38, 38, 46, 46, 13],
       [24,  3, 54, 18, 47],
       [ 4, 42,  8, 66, 50]])

In [53]:
r=np.random.rand(3,5) 
r #rand - gives no in any described shape and the value btw 0 to 1

array([[0.28643533, 0.55561256, 0.37642024, 0.02662436, 0.49414912],
       [0.83471509, 0.36698733, 0.51538211, 0.47237913, 0.38615209],
       [0.744137  , 0.33524208, 0.59543829, 0.31613338, 0.34625042]])

In [5]:
np.random.randn(3,5) # any random value 

array([[-0.82685369, -1.23445728,  0.5383442 , -1.32676583, -0.50974678],
       [ 0.05881234, -0.95782642,  1.1194232 , -2.10593819,  0.52517248],
       [-0.93202832,  1.08576501,  0.01802415, -0.45832856, -1.0140945 ]])

In [56]:
import random

In [4]:


np.loadtxt('data.txt',dtype='str') #Read text file


array(['hii', 'nirmiti'], dtype='<U7')

In [6]:
np.loadtxt('data1.txt',delimiter=',') #Read text file


array([[ 45.,  65.,  74.,  98.],
       [ 23., 511.,  64.,  48.],
       [ 20.,  40.,  90.,  60.]])

In [7]:
a=np.random.randint(10,1000,[3,5])
a

array([[550, 353, 334, 891, 774],
       [730, 844, 394, 249, 817],
       [ 93, 717, 276, 547, 799]])

In [9]:
np.savetxt('data3.txt',a,delimiter='|',fmt='%d') # write text file

In [10]:

a

array([[550, 353, 334, 891, 774],
       [730, 844, 394, 249, 817],
       [ 93, 717, 276, 547, 799]])

In [12]:
sum(sum(a))

8368

In [13]:
a.sum()

8368

In [15]:
a.sum(axis=1) #stastical function mein row =1 

array([2902, 3034, 2432])

In [16]:
a.sum(axis=0)   #column-wise

array([1373, 1914, 1004, 1687, 2390])

In [17]:
a.mean(axis=1)

array([580.4, 606.8, 486.4])

In [18]:
a.max(axis=1)

array([891, 844, 799])

In [19]:
a.argmax(axis=1)  # index of max value 

array([3, 1, 4], dtype=int64)

In [20]:
a.argmin(axis=1)

array([2, 3, 0], dtype=int64)

In [21]:
a.argmax()

3

In [22]:
a.flatten()

array([550, 353, 334, 891, 774, 730, 844, 394, 249, 817,  93, 717, 276,
       547, 799])